/**
 * Pure deterministic ranking engine for Phase 11B: Personalized Intelligence Feed.
 * 
 * Rules:
 * - Direct Event Follow: +120
 * - Topic Follow: +45 for 1st match, +25 for each additional match (max +95)
 * - Source Follow: +20 per match (max +40)
 * - Narrative Evolution: +35 (has_narrative_delta OR brief_version >= 2)
 * - Cross-Source Perspectives: +25 (has_claim_comparison AND source_count >= 2)
 * - Freshness: 'developing' -> +30, 'active' -> +15, 'stale' -> 0
 * - Coverage: >=3 sources -> +20, 2 sources -> +10, <=1 source -> 0
 * - Severity: 'critical' -> +15, 'warning' | 'high' -> +10, other -> 0
 * - Time Decay: -1.5 pts per completed 12-hour interval since last_published_at (max penalty -30)
 * - Final Score: Math.max(0, sumOfPositiveScores - decay)
 * 
 * Explainability reasons are generated by the SAME evaluation logic.
 */

export type RankingFreshness = 'developing' | 'active' | 'stale';

export interface RankingEvent {
  id: number;
  hash: string;
  last_published_at: number | null;
  article_count: number;
  source_count: number;
  freshness: RankingFreshness;
  severity: string | null;
  brief_version: number;
  has_narrative_delta: boolean;
  has_claim_comparison: boolean;
  topic_slugs: string[];
  source_names: string[];
}

export interface FollowContext {
  eventIds: Set<string>;
  topicSlugs: Set<string>;
  sourceNames: Set<string>;
}

export interface RankedScore {
  score: number;
  rank_reasons: string[];
  follow_score: number;
}

export interface RankedEvent<T extends RankingEvent = RankingEvent> {
  event: T;
  score: number;
  rank_reasons: string[];
  follow_score: number;
}

/**
 * Evaluates the deterministic score and explainability reasons for a single event.
 */
export function scoreEvent(
  event: RankingEvent,
  follows: FollowContext,
  nowSeconds: number
): RankedScore {
  let positiveScore = 0;
  let followScore = 0;
  const reasons: string[] = [];

  // 1. Direct Event Follow (+120)
  if (follows.eventIds.has(event.hash)) {
    positiveScore += 120;
    followScore += 120;
    reasons.push('Following Event');
  }

  // 2. Topic Follow (+45 1st, +25 each additional, max +95)
  const matchedTopics: string[] = [];
  const seenTopics = new Set<string>();
  for (const slug of event.topic_slugs) {
    const normalized = slug.trim().toLowerCase();
    if (normalized && follows.topicSlugs.has(normalized) && !seenTopics.has(normalized)) {
      seenTopics.add(normalized);
      matchedTopics.push(slug);
    }
  }

  if (matchedTopics.length > 0) {
    const topicPoints = Math.min(95, 45 + (matchedTopics.length - 1) * 25);
    positiveScore += topicPoints;
    followScore += topicPoints;

    // Display cap of 2 to avoid flooding UI badges
    const displayTopics = matchedTopics.slice(0, 2);
    for (const t of displayTopics) {
      reasons.push(`Topic: ${t}`);
    }
  }

  // 3. Source Follow (+20 per matching source, max +40)
  const matchedSources: string[] = [];
  const seenSources = new Set<string>();
  for (const src of event.source_names) {
    const normalized = src.trim().toLowerCase();
    if (normalized && follows.sourceNames.has(normalized) && !seenSources.has(normalized)) {
      seenSources.add(normalized);
      matchedSources.push(src);
    }
  }

  if (matchedSources.length > 0) {
    const sourcePoints = Math.min(40, matchedSources.length * 20);
    positiveScore += sourcePoints;
    followScore += sourcePoints;

    // Display cap of 2 to avoid flooding UI badges
    const displaySources = matchedSources.slice(0, 2);
    for (const s of displaySources) {
      reasons.push(`Source: ${s}`);
    }
  }

  // 4. Narrative Evolution (+35)
  const isEvolved = event.has_narrative_delta || event.brief_version >= 2;
  if (isEvolved) {
    positiveScore += 35;
    const versionLabel = event.brief_version >= 2 ? `V${event.brief_version}` : 'V2+';
    reasons.push(`Narrative Evolved (${versionLabel})`);
  }

  // 5. Cross-Source Perspectives (+25)
  if (event.has_claim_comparison && event.source_count >= 2) {
    positiveScore += 25;
    reasons.push('Cross-Source Perspectives');
  }

  // 6. Freshness (Developing +30, Active +15, Stale 0)
  if (event.freshness === 'developing') {
    positiveScore += 30;
    reasons.push('Developing Story');
  } else if (event.freshness === 'active') {
    positiveScore += 15;
  }

  // 7. Coverage Breadth (>=3 sources +20, 2 sources +10, <=1 0)
  if (event.source_count >= 3) {
    positiveScore += 20;
    reasons.push('Broad Multi-Source Coverage');
  } else if (event.source_count === 2) {
    positiveScore += 10;
  }

  // 8. Severity Weight (critical +15, warning/high +10)
  const sev = event.severity?.toLowerCase() ?? '';
  if (sev === 'critical') {
    positiveScore += 15;
    reasons.push('High Severity Alert');
  } else if (sev === 'warning' || sev === 'high') {
    positiveScore += 10;
    reasons.push('High Severity Alert');
  }

  // 9. Time Decay (-1.5 per completed 12-hour interval, max 30)
  let decay = 0;
  if (event.last_published_at !== null && event.last_published_at <= nowSeconds) {
    const elapsed = Math.max(0, nowSeconds - event.last_published_at);
    const intervals = Math.floor(elapsed / 43200); // 12 hours = 43200 seconds
    decay = Math.min(30, intervals * 1.5);
  }

  const finalScore = Math.max(0, positiveScore - decay);

  // Fallback reason if no reasons emitted and event is active/recent
  if (reasons.length === 0 && event.freshness !== 'stale') {
    reasons.push('Top Active Story');
  }

  return {
    score: finalScore,
    rank_reasons: reasons,
    follow_score: followScore,
  };
}

/**
 * Deterministic tie-breaking comparator for ranked events.
 * 1. score DESC
 * 2. last_published_at DESC (nulls last)
 * 3. article_count DESC
 * 4. id DESC
 */
export function compareRankedEvents<T extends RankingEvent>(
  a: RankedEvent<T>,
  b: RankedEvent<T>
): number {
  if (b.score !== a.score) {
    return b.score - a.score;
  }
  const aTime = a.event.last_published_at ?? 0;
  const bTime = b.event.last_published_at ?? 0;
  if (bTime !== aTime) {
    return bTime - aTime;
  }
  if (b.event.article_count !== a.event.article_count) {
    return b.event.article_count - a.event.article_count;
  }
  return b.event.id - a.event.id;
}

/**
 * Ranks a collection of candidate events against follow context deterministically.
 */
export function rankEvents<T extends RankingEvent>(
  events: T[],
  follows: FollowContext,
  nowSeconds: number
): RankedEvent<T>[] {
  const scored = events.map(event => {
    const res = scoreEvent(event, follows, nowSeconds);
    return {
      event,
      score: res.score,
      rank_reasons: res.rank_reasons,
      follow_score: res.follow_score,
    };
  });

  return scored.sort(compareRankedEvents);
}
